public class Open_Cage_GeoCode_Wrapper{
	public results[] results;

	public class results {
		public components components;
		public String formatted;	//unnamed road, Basheer Bagh, Hyderabad - 500063, Telangana, India
		public geometry geometry;
	}
	public class components {
		public String city;	//Hyderabad
		public String city_district;	//Greater Hyderabad Municipal Corporation Central Zone
		public String continent;	//Asia
		public String country;	//India
		public String country_code;	//in
		public String county;	//Himayatnagar mandal
		public String postcode;	//500063
		public String road;	//unnamed road
		public String road_type;	//primary
		public String state;	//Telangana
		public String state_code;	//TG
		public String state_district;	//Hyderabad
		public String suburb;	//Basheer Bagh
	}
	 public class geometry {
		public Double lat;	//17.4064836
		public Double lng;	//78.4771982
	}

}